pygments: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
baseurl: /alt
navigation:
- name: me
  href: '#me'
  class: fa-home
  include: true
- name: projects
  href: '#projects'
  class: fa-coffee
  include: true
- name: blog
  href: '#blog'
  class: fa-bullhorn
  include: true
- name: CV
  href: CV_AndreaKaplan.pdf
  class: fa-file-text-o
  include: false
  target: _blank
- name: github
  href: http://github.com/andeek
  class: fa-github
  include: false
  target: _blank
- name: twitter
  href: http://twitter.com/andeekaplan
  class: fa-twitter
  include: false
  target: _blank
